module.exports = {
  COOKIE_KEY: process.env.COOKIE_KEY,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_CALLBACK: process.env.GOOGLE_CLIENT_CALLBACK,

  MONGO_URI: process.env.MONGO_URI,
};
